Algoritmo "media"

Var
nota1:real
nota2:real
nota3:real
nota4:real
media:real

Inicio
Escreva("Digite a nota da primeira matéria: ")
Leia(nota1)
Escreva("Digite a nota da segunda matéria: ")
Leia(nota2)
Escreva("Digite a nota da terceira matéria: ")
Leia(nota3)
Escreva("Digite a nota da quarta matéria: ")
Leia(nota4)
media <- (nota1+nota2+nota3+nota4) / 4
Escreva("O valor total da soma é de: ", media)

Fimalgoritmo